### ISSUE TITLE
Assets versioning with dates

### ISSUE THREAD

**Issue by CyrilLeMat** [Cornerstone-OnDemand/modelkit#101]
As of today, assets can only be versioned with numbers (eg: 1.4) 
https://cornerstone-ondemand.github.io/modelkit/assets/managing_assets/

Modelkit should support date versionning (eg: 2021-10-16) to support organisations where models are trained on a monthy/weekly/daily basis

**Comment by tgenin** [comment]
the most important is to design a way to custom the versioning (and maybe add a "simple" date versioning system as an example ?) 
because maybe some orga use `2021-10-16` but what about 2 update the same day ? overwrite ? `2021-10-16.incremental_number` ? `2021-10-16-hh-mm-ss` ? etc...

**Comment by CyrilLeMat** [comment]
I think overwrite is better:
- Having date + incremental_number seems too complex as date is already a versioning system
- If someone want a second precision, we could have a third "datetime" option
What do you think?

**Comment by victorbenichoux** [comment]
Overwriting would be dangerous since we strive for reproducible builds, and the whole assets system is designed under the assumption of immutable assets.

That being said, we should not overthink it: to adress the use case here, any set format is fine. Providing a customizable format can be implemented later. 

Using the ISO date format seems like the natural choice (using timezone information ofc), since we would not need to handle serialization, deserilaization and comparison that are part of the stdlib.

It is a relatively easy feature to implement...

**Comment by tgenin** [comment]
I will try something
